spring:
  config:
    import: classpath:config.properties
  r2dbc:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

todo:
  app:
    version: ${VERSION}
