CREATE TABLE IF NOT EXISTS TASK  (
                       ID BIGINT AUTO_INCREMENT PRIMARY KEY,
                       DESCRIPTION VARCHAR(255) NOT NULL ,
                       LABEL VARCHAR(255) NOT NULL,
                       CREATE_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                       UPDATE_AT  TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
